spring:
  application:
    name: FlyWayDemo

  datasource:
    hikari:
      jdbc-url: jdbc:h2:file:./data/testDB
      driver-class-name: org.h2.Driver
      username: sa
      password: password

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  flyway:
    enabled: true